
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-b1 # local-volum-Ali/Ahmad .......
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/local-volume-b1 # local-volum-Ali/Ahmad ....... path for storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-b1 # local-volum-Ali/Ahmad .......
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/local-volume-b1 # local-volum-Ali/Ahmad ....... path for storage
