apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: b1
  labels:
    app: mysql
    tier: backend
    env: development
spec:
  selector:
    app: mysql
    tier: backend
    env: development
  ports:
    - protocol: TCP
      port: 30022
  clusterIP: None
